package g3;

import android.R;

/* JADX INFO: loaded from: classes.dex */
public abstract class l {

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    public static final int[] f13677a = {R.attr.enabled, xyz.easypro.httpcustom.R.attr.bg, xyz.easypro.httpcustom.R.attr.bh, xyz.easypro.httpcustom.R.attr.c7, xyz.easypro.httpcustom.R.attr.kp, xyz.easypro.httpcustom.R.attr.l5, xyz.easypro.httpcustom.R.attr.m5, xyz.easypro.httpcustom.R.attr.m6, xyz.easypro.httpcustom.R.attr.m7, xyz.easypro.httpcustom.R.attr.m8, xyz.easypro.httpcustom.R.attr.m9, xyz.easypro.httpcustom.R.attr.m_, xyz.easypro.httpcustom.R.attr.ma, xyz.easypro.httpcustom.R.attr.mb, xyz.easypro.httpcustom.R.attr.mc, xyz.easypro.httpcustom.R.attr.md, xyz.easypro.httpcustom.R.attr.me, xyz.easypro.httpcustom.R.attr.mf, xyz.easypro.httpcustom.R.attr.mg, xyz.easypro.httpcustom.R.attr.mh, xyz.easypro.httpcustom.R.attr.mi, xyz.easypro.httpcustom.R.attr.mj, xyz.easypro.httpcustom.R.attr.mk, xyz.easypro.httpcustom.R.attr.ml, xyz.easypro.httpcustom.R.attr.mm, xyz.easypro.httpcustom.R.attr.mn, xyz.easypro.httpcustom.R.attr.mo, xyz.easypro.httpcustom.R.attr.mp, xyz.easypro.httpcustom.R.attr.ol, xyz.easypro.httpcustom.R.attr.ox, xyz.easypro.httpcustom.R.attr.uy, xyz.easypro.httpcustom.R.attr.zc, xyz.easypro.httpcustom.R.attr.a02, xyz.easypro.httpcustom.R.attr.a0l, xyz.easypro.httpcustom.R.attr.a0t, xyz.easypro.httpcustom.R.attr.a12, xyz.easypro.httpcustom.R.attr.a7n};

    /* JADX INFO: renamed from: b, reason: collision with root package name */
    public static final int[] f13678b = {xyz.easypro.httpcustom.R.attr.v6, xyz.easypro.httpcustom.R.attr.v7, xyz.easypro.httpcustom.R.attr.v8, xyz.easypro.httpcustom.R.attr.v9, xyz.easypro.httpcustom.R.attr.v_, xyz.easypro.httpcustom.R.attr.va, xyz.easypro.httpcustom.R.attr.vb, xyz.easypro.httpcustom.R.attr.vc, xyz.easypro.httpcustom.R.attr.vd, xyz.easypro.httpcustom.R.attr.ve, xyz.easypro.httpcustom.R.attr.vf, xyz.easypro.httpcustom.R.attr.vg, xyz.easypro.httpcustom.R.attr.vh, xyz.easypro.httpcustom.R.attr.vi, xyz.easypro.httpcustom.R.attr.vj, xyz.easypro.httpcustom.R.attr.vk, xyz.easypro.httpcustom.R.attr.vl, xyz.easypro.httpcustom.R.attr.vm, xyz.easypro.httpcustom.R.attr.vn, xyz.easypro.httpcustom.R.attr.vo, xyz.easypro.httpcustom.R.attr.vp, xyz.easypro.httpcustom.R.attr.vq, xyz.easypro.httpcustom.R.attr.vr, xyz.easypro.httpcustom.R.attr.vs, xyz.easypro.httpcustom.R.attr.vt, xyz.easypro.httpcustom.R.attr.vu, xyz.easypro.httpcustom.R.attr.vv, xyz.easypro.httpcustom.R.attr.vw, xyz.easypro.httpcustom.R.attr.vx, xyz.easypro.httpcustom.R.attr.vy, xyz.easypro.httpcustom.R.attr.vz, xyz.easypro.httpcustom.R.attr.w0, xyz.easypro.httpcustom.R.attr.w1, xyz.easypro.httpcustom.R.attr.w2, xyz.easypro.httpcustom.R.attr.w3, xyz.easypro.httpcustom.R.attr.w4, xyz.easypro.httpcustom.R.attr.w5, xyz.easypro.httpcustom.R.attr.w6, xyz.easypro.httpcustom.R.attr.w7};
}
